// app/page.tsx
import { Icon } from "@iconify/react";
import Link from "next/link";

export default function Home() {
	return (
		<div className="flex flex-col flex-1 items-center justify-center font-sans text-center">
			<h1 className="text-6xl font-bold">
				Data Structures and Algorithms
				<br /> Visualizer Platform
			</h1>
			<p className="text-lg py-8 text-slate-400">
				The DSA Visualizer Platform aims to bridge this gap by providing
				an interactive environment where users can perform operations,
				<br />
				an interactive environment where users can perform operations,
				observe execution in real time, analyze complexity, and connect
				<br />
				theoretical concepts with practical implementations.
			</p>
			<div>
				<Link href={"/array"}>
					<button className="cursor-pointer px-3 py-1 rounded-lg bg-green-400 dark:text-slate-800 flex flex-row items-center gap-2 text-lg">
						Array <Icon icon={"lucide:arrow-right"} fontSize={20} />
					</button>
				</Link>
			</div>
		</div>
	);
}

// app/app.vue
<script setup>
import applogo from "/applogo.svg";

useHead({
	meta: [
		{ name: "viewport", content: "width=device-width, initial-scale=1" },
	],
	link: [{ rel: "icon", href: "/favicon.ico" }],
	htmlAttrs: {
		lang: "en",
	},
});

const title = "Data Structures and Algorithms Visualizer Platform";
const description =
	"The DSA Visualizer Platform aims to bridge this gap by providing an interactive environment where users can perform operations, observe execution in real time, analyze complexity, and connect theoretical concepts with practical implementations.";

useSeoMeta({
	title,
	description,
	ogTitle: title,
	ogDescription: description,
	ogImage: applogo,
	twitterCard: "summary_large_image",
});
</script>

<template>
	<UApp>
		<UHeader>
			<template #left>
				<NuxtLink to="/">
					<AppLogo class="w-auto h-10 shrink-0" />
				</NuxtLink>
			</template>
		</UHeader>

		<NuxtLayout />

		<USeparator icon="i-simple-icons-nuxtdotjs" />

		<UFooter>
			<template #left>
				<p class="text-sm text-muted">
					Built by BhJaipal • © {{ new Date().getFullYear() }}
					<UButton
						to="https://codeberg.org/BhJaipal"
						target="_blank"
						icon="i-simple-icons-codeberg"
						aria-label="GitHub"
						color="neutral"
						variant="ghost"
					/><UButton
						to="https://github.com/BhJaipal"
						target="_blank"
						icon="i-simple-icons-github"
						aria-label="GitHub"
						color="neutral"
						variant="ghost"
					/>
				</p>
			</template>

			<template #right>
				<UButton
					to="https://github.com/BhJaipal/dsa-visualizor"
					target="_blank"
					label="Source"
					icon="i-simple-icons-github"
					aria-label="GitHub"
					color="neutral"
					variant="ghost"
				/>
			</template>
		</UFooter>
	</UApp>
</template>
